map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

resolver 127.0.0.11 valid=30s ipv6=off;

server_tokens off;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 1d;
ssl_session_tickets off;
