INSERT INTO categories (id, parent_id, name, slug, description, ai_description, ai_keywords, enabled, system_category, sort_order, created_at, updated_at) VALUES
(1, NULL, '计算机基础', 'computer-science', '计算机科学基础知识', '计算机组成、数据结构、操作系统、网络和编译原理等基础主题', '计算机原理,算法,操作系统,网络,编译器', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, NULL, '编程语言', 'programming-languages', '编程语言相关内容', '语言语法、运行时、编译、工具链和语言实践', 'Java,C++,C,汇编,JavaScript,TypeScript', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, NULL, '开发框架', 'frameworks', '开发框架和生态', '具体开发框架、库、生态和框架使用实践', 'Spring,ORM,RPC,微服务,Web,前端', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, NULL, '软件设计与架构', 'software-architecture', '设计、架构和工程质量', '跨语言的软件设计、系统架构、测试、性能与质量实践', '设计模式,架构,性能,测试,重构', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, NULL, '数据与中间件', 'data-middleware', '数据库及中间件', '数据存储、缓存、消息、检索等基础设施软件', '数据库,缓存,MQ,搜索,存储', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, NULL, '系统与基础设施', 'infrastructure', '系统和基础设施', 'Linux、容器、交付、监控和云环境', 'Linux,Docker,Kubernetes,CI/CD,监控', TRUE, FALSE, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, NULL, 'AI 与开发工具', 'ai-tools', 'AI 与效率工具', '大模型应用、AI 编程以及日常开发工具', 'LLM,AI,IDE,编辑器,Maven,Gradle', TRUE, FALSE, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, NULL, '未分类', 'uncategorized', '尚未确定分类的文章', '只在其他分类均不匹配或置信度过低时选择', '其他,无法判断', TRUE, TRUE, 999, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO categories (id, parent_id, name, slug, ai_description, ai_keywords, enabled, system_category, sort_order, created_at, updated_at) VALUES
(101, 1, '组成原理', 'computer-architecture', 'CPU、存储、总线、指令集和硬件工作原理', 'CPU,内存,缓存,指令集,硬件', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 1, '数据结构与算法', 'data-structures-algorithms', '数据结构、算法设计、复杂度和算法题', '数据结构,算法,复杂度,排序,图', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 1, '操作系统', 'operating-systems', '进程、线程、内存、文件系统和操作系统机制', '进程,线程,内存管理,文件系统,内核', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 1, '计算机网络', 'computer-networks', '网络协议、HTTP、TCP/IP 和网络编程原理', 'TCP,UDP,HTTP,DNS,协议', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 1, '编译原理', 'compiler-theory', '词法、语法、IR、优化、代码生成和编译器', '编译器,词法,语法,IR,代码生成', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(201, 2, 'Java', 'java', 'Java 语言、JVM、并发和标准库', 'Java,JVM,字节码,并发,JDK', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(202, 2, 'C/C++', 'c-cpp', 'C、C++、内存模型和工具链', 'C,C++,指针,内存,STL', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(203, 2, '汇编', 'assembly', '汇编语言、机器码和底层调试', '汇编,机器码,寄存器,x86,ARM', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(204, 2, 'JavaScript/TypeScript', 'javascript-typescript', 'JavaScript、TypeScript 语言和运行时', 'JavaScript,TypeScript,Node.js,V8', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(205, 2, '其他语言', 'other-languages', '未单独列出的编程语言', 'Python,Go,Rust,Kotlin,语言', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(301, 3, 'Spring 生态', 'spring', 'Spring Framework、Spring Boot、Spring Cloud 和 Spring AI', 'Spring,Spring Boot,Spring Cloud,Spring AI', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(302, 3, 'ORM 与数据库框架', 'orm-database-frameworks', 'JPA、Hibernate、MyBatis 和数据库访问框架', 'JPA,Hibernate,MyBatis,ORM,JDBC', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(303, 3, 'RPC 与微服务', 'rpc-microservices', 'RPC、服务治理、网关和微服务框架', 'RPC,微服务,网关,注册中心,服务治理', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(304, 3, 'Web 与前端框架', 'web-frontend-frameworks', 'Web MVC、React、Vue 等 Web 框架', 'Web,React,Vue,MVC,前端', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(305, 3, '其他框架', 'other-frameworks', '其他难以归入现有子类的开发框架', '框架,库,SDK', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(401, 4, '设计模式', 'design-patterns', '面向对象设计原则和设计模式', '设计模式,SOLID,DDD,重构', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(402, 4, '系统架构', 'system-architecture', '分布式系统、系统设计和架构决策', '系统设计,分布式,架构,高可用', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(403, 4, '性能优化', 'performance', '性能分析、基准、调优和容量', '性能,调优,基准,延迟,吞吐量', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(404, 4, '测试', 'testing', '单元测试、集成测试和测试方法', '测试,JUnit,Mock,集成测试,TDD', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(405, 4, '工程质量', 'engineering-quality', '代码质量、评审、规范和可维护性', '代码质量,规范,评审,可维护性', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(501, 5, '关系型数据库', 'relational-databases', 'SQL 和关系型数据库', 'SQL,MySQL,PostgreSQL,H2,事务', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(502, 5, 'NoSQL', 'nosql', '文档、列式、图等非关系数据库', 'NoSQL,MongoDB,Cassandra,图数据库', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(503, 5, '缓存', 'caching', '缓存原理和缓存系统', '缓存,Redis,Caffeine,一致性', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(504, 5, '消息队列', 'message-queues', '异步消息、事件流和消息中间件', 'Kafka,RabbitMQ,MQ,事件流', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(505, 5, '搜索与存储', 'search-storage', '搜索引擎、文件和对象存储', 'Elasticsearch,Lucene,对象存储,文件系统', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(601, 6, 'Linux', 'linux', 'Linux 系统管理、Shell 和内核工具', 'Linux,Shell,systemd,内核', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(602, 6, '容器与编排', 'containers-orchestration', '容器、镜像和容器编排', 'Docker,Kubernetes,容器,镜像', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(603, 6, 'CI/CD', 'ci-cd', '持续集成、构建、发布和自动化', 'CI,CD,Jenkins,GitHub Actions,发布', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(604, 6, '可观测性', 'observability', '日志、指标、追踪和告警', '日志,指标,Tracing,Prometheus,告警', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(605, 6, '云服务', 'cloud-services', '云平台及云原生服务', '云,AWS,Azure,阿里云,Serverless', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(701, 7, '大模型应用', 'llm-applications', '大模型 API、Agent、Prompt 和应用开发', 'LLM,Agent,Prompt,RAG,模型API', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(702, 7, 'AI 编程', 'ai-coding', 'AI 辅助开发、代码生成和编程代理', 'AI编程,Codex,Copilot,代码生成', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(703, 7, 'IDE 与编辑器', 'ide-editors', 'IDE、编辑器及其插件与配置', 'IDE,IntelliJ,VS Code,Vim,编辑器', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(704, 7, '构建工具', 'build-tools', '构建、依赖管理和打包工具', 'Maven,Gradle,CMake,npm,构建', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(705, 7, '效率工具', 'productivity-tools', '版本控制、命令行和其他开发效率工具', 'Git,命令行,效率,工具', TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES
('site.name', '纸上代码', CURRENT_TIMESTAMP),
('site.subtitle', '记录软件开发与计算机技术', CURRENT_TIMESTAMP),
('site.author', '', CURRENT_TIMESTAMP),
('site.footer', '由 Paper Blog 驱动', CURRENT_TIMESTAMP),
('site.about', '# 关于\n\n这是一个轻量级个人技术博客。', CURRENT_TIMESTAMP),
('site.page-size', '10', CURRENT_TIMESTAMP);
