CREATE TABLE ai_execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    model VARCHAR(120) NOT NULL,
    endpoint_identifier VARCHAR(200) NOT NULL,
    elapsed_ms BIGINT NOT NULL,
    input_tokens BIGINT,
    output_tokens BIGINT,
    parse_status VARCHAR(30) NOT NULL,
    category_id BIGINT,
    confidence DOUBLE PRECISION,
    result_tags VARCHAR(500),
    suggested_category VARCHAR(200),
    error_type VARCHAR(80),
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_log_job FOREIGN KEY (job_id) REFERENCES ai_jobs(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_execution_log_created ON ai_execution_logs(created_at DESC);
