CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    ai_description VARCHAR(1000),
    ai_exclusions VARCHAR(1000),
    ai_examples VARCHAR(2000),
    ai_keywords VARCHAR(1000),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    system_category BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_category_slug UNIQUE (slug),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    normalized_name VARCHAR(60) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    created_by VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tag_normalized_name UNIQUE (normalized_name),
    CONSTRAINT uk_tag_slug UNIQUE (slug)
);

CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    summary VARCHAR(1000),
    content CLOB NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    content_form VARCHAR(20) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    rendered_html CLOB,
    render_version INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL,
    category_id BIGINT NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    seo_title VARCHAR(200),
    seo_description VARCHAR(500),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    classification_source VARCHAR(20) NOT NULL,
    classification_status VARCHAR(20) NOT NULL,
    classification_confidence DOUBLE PRECISION,
    classification_reason VARCHAR(1000),
    classification_locked BOOLEAN NOT NULL DEFAULT FALSE,
    classified_content_hash VARCHAR(64),
    classified_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_article_public ON articles(status, kind, pinned, published_at);
CREATE INDEX idx_article_category ON articles(category_id, status, published_at);
CREATE INDEX idx_article_content_form ON articles(content_form, status, published_at);

CREATE TABLE article_tags (
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE article_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    content_form VARCHAR(20) NOT NULL,
    reason VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_revision_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE INDEX idx_revision_article ON article_revisions(article_id, created_at DESC);

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    width INT,
    height INT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_media_path UNIQUE (relative_path)
);

CREATE TABLE ai_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    error_type VARCHAR(80),
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_job_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_job_queue ON ai_jobs(status, available_at);

CREATE TABLE ai_execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    model VARCHAR(120) NOT NULL,
    endpoint_identifier VARCHAR(200) NOT NULL,
    elapsed_ms BIGINT NOT NULL,
    input_tokens BIGINT,
    output_tokens BIGINT,
    parse_status VARCHAR(30) NOT NULL,
    category_slug VARCHAR(100),
    content_form VARCHAR(20),
    confidence DOUBLE PRECISION,
    result_tags VARCHAR(500),
    suggested_category VARCHAR(200),
    error_type VARCHAR(80),
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_log_job FOREIGN KEY (job_id) REFERENCES ai_jobs(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_execution_log_created ON ai_execution_logs(created_at DESC);

CREATE TABLE ai_settings (
    id BIGINT PRIMARY KEY,
    document CLOB NOT NULL
);

CREATE TABLE backup_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500),
    file_size BIGINT,
    sha256 VARCHAR(64),
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE site_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value CLOB,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO categories (id, parent_id, name, slug, description, ai_description, ai_exclusions, ai_examples, ai_keywords, enabled, system_category, sort_order, created_at, updated_at) VALUES
(10, NULL, '技术与创造', 'technology-creation', '代码、系统、AI、工具，以及把想法做成东西的过程。', '以技术知识、工程实践、数字工具或产品创造为主要内容。', '单纯工作情绪归入工作与成长；不以技术为重点的日常体验归入生活与见闻。', 'Java 实践；操作系统原理；使用 AI 工具；独立项目复盘', '技术,编程,计算机,AI,工具,产品,项目', TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, NULL, '生活与见闻', 'life-observations', '生活碎片、成长经历、旅行见闻与个人兴趣。', '以亲身经历、日常场景、生活兴趣或所见所闻为主要内容。', '抽象观点归入思考与表达；作品评论归入阅读与审美。', '今日小记；一次旅行；做饭心得；职业成长记录', '日常,生活,工作,成长,旅行,兴趣', TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, NULL, '思考与表达', 'thoughts-expression', '随笔、观点、感悟，以及短小而想留下的表达。', '以作者的感受、思考、观点或原创表达为主要内容。', '以外部作品为中心的赏析归入阅读与审美；纯粹生活流水账归入日常片段。', '关于选择的随笔；社会话题评论；一句原创短诗', '随笔,感悟,观点,评论,片语,原创,诗', TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, NULL, '阅读与审美', 'reading-aesthetics', '读过、看过、听过，以及值得收藏的文字与作品。', '以书籍、影视、音乐、诗词文学或外部摘录为主要对象。', '作者自己的短句和诗归入片语与诗；一般兴趣活动归入兴趣爱好。', '读书笔记；电影观后感；古诗赏析；带出处的摘录', '阅读,书籍,影视,音乐,文学,诗词,摘录', TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(90, NULL, '未分类', 'uncategorized', '暂时无法确定主要意图的内容。', '仅当所有其他分类都不匹配，或内容缺少到无法判断主要意图时使用。', '不能因为内容很短、不专业、非技术、原创比例低或只有一句话就选择未分类。', '无上下文且无法辨认含义的占位文本', '无法判断,待整理', TRUE, TRUE, 999, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO categories (id, parent_id, name, slug, description, ai_description, ai_exclusions, ai_examples, ai_keywords, enabled, system_category, sort_order, created_at, updated_at) VALUES
(101, 10, '软件开发', 'software-development', '编程语言、框架、代码实现、测试与工程实践。', '正文主要在讲写代码、语言特性、框架使用、API、调试、测试或软件工程方法。', '以硬件、操作系统或网络机制为中心时归入计算机与系统；以 AI 工具体验为中心时归入 AI 与数字工具。', 'Java Stream 用法；C++ 内存管理；Spring Boot 接口设计；汇编代码分析', 'Java,C++,C,汇编,Spring,框架,代码,API,测试,调试', TRUE, FALSE, 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 10, '计算机与系统', 'computer-systems', '计算机原理、算法、操作系统、网络与基础设施。', '正文主要解释计算机基础原理、数据结构与算法、体系结构、操作系统、网络、数据库机制或基础设施。', '以具体业务代码和框架教程为中心时归入软件开发；以使用大模型为中心时归入 AI 与数字工具。', 'CPU 缓存原理；Linux 进程调度；TCP 拥塞控制；算法复杂度；Docker 运行机制', '计算机原理,算法,CPU,操作系统,Linux,网络,数据库,容器,基础设施', TRUE, FALSE, 102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 10, 'AI 与数字工具', 'ai-digital-tools', '大模型、AI 应用、软件工具与数字工作流。', '正文主要讨论大模型、Prompt、Agent、AI 应用，或数字工具、编辑器和效率工作流。', '普通软件框架教程归入软件开发；产品从构想到落地的完整复盘归入产品与项目。', '大模型 API 接入；Codex 使用心得；知识管理工具；自动化工作流', 'AI,LLM,大模型,Agent,Prompt,Codex,数字工具,效率,自动化', TRUE, FALSE, 103, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 10, '产品与项目', 'products-projects', '产品想法、独立项目、设计取舍与实践复盘。', '正文主要讲一个产品或项目的目标、过程、设计决策、进展、发布或复盘。', '只讲某项技术知识时归入软件开发或计算机与系统；只讲职场成长时归入工作与成长。', '个人博客改版复盘；独立应用从想法到发布；产品需求取舍', '产品,项目,需求,设计,复盘,发布,独立开发', TRUE, FALSE, 104, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(201, 20, '日常片段', 'daily-moments', '普通日子里值得记住的小事与即时感受。', '以当天生活、具体场景、心情、小事件或轻量近况为主要内容。', '较完整的抽象感悟归入随笔感悟；原创短诗或凝练句子归入片语与诗。', '今天下雨了；周末做了一顿饭；窗边看到一只猫', '今日,日常,周末,生活,心情,小记,近况', TRUE, FALSE, 201, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(202, 20, '工作与成长', 'work-growth', '职业经历、学习过程、习惯与个人成长。', '以工作经历、职业选择、学习方法、习惯改变或个人成长为主要内容。', '具体技术教程归入技术与创造；宏观社会评论归入观点评论。', '一次面试复盘；如何安排学习；换工作的感受；习惯养成记录', '工作,职场,职业,学习,成长,习惯,面试', TRUE, FALSE, 202, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(203, 20, '旅行见闻', 'travel-notes', '旅途、地点、风景与路上的故事。', '以旅行过程、地点体验、路线、风景、人文见闻或出行记录为主要内容。', '单纯摄影技巧归入兴趣爱好；针对城市政策或事件的评论归入观点评论。', '杭州两日散步；山里露营；一次独自旅行；城市印象', '旅行,游记,城市,风景,路线,露营,出行', TRUE, FALSE, 203, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(204, 20, '兴趣爱好', 'hobbies', '摄影、运动、美食、手作、游戏、宠物等个人兴趣。', '以个人兴趣活动、实践体验或爱好心得为主要内容。', '影视音乐作品评论归入影视音乐；以旅行地点为主归入旅行见闻。', '摄影练习；跑步记录；咖啡冲煮；养猫日记；游戏体验', '摄影,运动,美食,手作,游戏,宠物,咖啡,跑步', TRUE, FALSE, 204, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(301, 30, '随笔感悟', 'essays-reflections', '从经历生长出的感受、联想与自我对话。', '以个人感受、人生思考、内心变化或散文式表达为主要内容，通常不强调论证结论。', '短小凝练的单句或诗性表达归入片语与诗；明确主张和论证归入观点评论。', '关于告别的随笔；对时间的感受；一次失眠后的联想', '随笔,感悟,心境,人生,散文,思考,自我', TRUE, FALSE, 301, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(302, 30, '观点评论', 'opinions-commentary', '对事件、现象与议题的判断和讨论。', '正文围绕某个议题提出较明确的判断、立场、分析或评论。', '以个人情绪和联想为主、没有论证诉求时归入随笔感悟；作品观后感归入对应审美分类。', '对远程工作的看法；评论一种社会现象；关于隐私的观点', '观点,评论,看法,议题,现象,立场,分析', TRUE, FALSE, 302, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(303, 30, '片语与诗', 'snippets-poetry', '原创短句、片语、短诗与难以展开却值得留下的表达。', '内容是作者自己的短句、诗性表达、短诗、灵感片段或极短感受；长度短不是降低分类置信度的理由。', '明确标注作者或出处的外部文字归入摘录收藏；对古诗或文学作品的赏析归入诗词文学。', '月光落进杯里；一首原创小诗；两三句突然想到的话', '片语,短句,短诗,诗,灵感,一句话,原创', TRUE, FALSE, 303, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(401, 40, '读书笔记', 'reading-notes', '关于书籍的摘要、批注、体会与延伸思考。', '正文围绕一本或多本书的内容、阅读过程、书评、批注或读后思考展开。', '只有少量外部原文且主要为了收藏时归入摘录收藏；文学文本本身的赏析可归入诗词文学。', '一本书的读后感；章节笔记；阅读清单；作者观点整理', '读书,书评,阅读,章节,作者,读后感,笔记', TRUE, FALSE, 401, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(402, 40, '影视音乐', 'film-music', '电影、剧集、纪录片、音乐与播客。', '正文主要记录或评论电影、电视剧、纪录片、音乐、专辑、演出或播客。', '一般娱乐活动或游戏体验归入兴趣爱好；以社会议题论证为主时归入观点评论。', '电影观后感；一张专辑的听后感；播客推荐；演出记录', '电影,影视,剧集,纪录片,音乐,专辑,播客,演出', TRUE, FALSE, 402, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(403, 40, '诗词文学', 'poetry-literature', '诗词、小说、散文等文学作品的阅读与赏析。', '正文以诗词或文学作品为对象，包含赏析、解读、背景、翻译或文学讨论。', '作者自己的诗性短句归入片语与诗；只保存带出处原文而无明显赏析时归入摘录收藏。', '古诗赏析；小说人物分析；一段散文的解读；文学流派随记', '古诗,诗词,文学,小说,散文,赏析,解读,翻译', TRUE, FALSE, 403, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(404, 40, '摘录收藏', 'excerpt-collection', '带出处保存的外部文字、语录、资料片段与清单。', '主要内容来自他人或外部来源，目的在于保存、整理或分享，并能识别作者、书名、链接或出处。', '无法确认来自外部来源的原创式短句归入片语与诗；包含充分个人分析的书籍内容归入读书笔记。', '《书名》摘录；某位作者的语录；附链接的资料片段；引用合集', '摘录,语录,引用,出处,作者,书名,收藏,原文', TRUE, FALSE, 404, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE categories ALTER COLUMN id RESTART WITH 1000;

INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES
('site.name', '小茹茹博客', CURRENT_TIMESTAMP),
('site.subtitle', '记录日常、技术、思考与喜欢的事', CURRENT_TIMESTAMP),
('site.author', '', CURRENT_TIMESTAMP),
('site.footer', '由 rurublog 驱动', CURRENT_TIMESTAMP),
('site.about', '# 关于\n\n这里是小茹茹博客。写日常，也写技术；收藏喜欢的文字，也记录还没想明白的事。', CURRENT_TIMESTAMP),
('site.page-size', '10', CURRENT_TIMESTAMP);
