CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    ai_description VARCHAR(1000),
    ai_keywords VARCHAR(1000),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    system_category BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_category_slug UNIQUE (slug),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    normalized_name VARCHAR(60) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    created_by VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tag_normalized_name UNIQUE (normalized_name),
    CONSTRAINT uk_tag_slug UNIQUE (slug)
);

CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    summary VARCHAR(1000),
    content CLOB NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    rendered_html CLOB,
    render_version INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL,
    category_id BIGINT NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    seo_title VARCHAR(200),
    seo_description VARCHAR(500),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    classification_source VARCHAR(20) NOT NULL,
    classification_status VARCHAR(20) NOT NULL,
    classification_confidence DOUBLE PRECISION,
    classification_reason VARCHAR(1000),
    classification_locked BOOLEAN NOT NULL DEFAULT FALSE,
    classified_content_hash VARCHAR(64),
    classified_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_article_public ON articles(status, kind, pinned, published_at);
CREATE INDEX idx_article_category ON articles(category_id, status, published_at);

CREATE TABLE article_tags (
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE article_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    reason VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_revision_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE INDEX idx_revision_article ON article_revisions(article_id, created_at DESC);

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    width INT,
    height INT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_media_path UNIQUE (relative_path)
);

CREATE TABLE ai_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    error_type VARCHAR(80),
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_job_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_job_queue ON ai_jobs(status, available_at);

CREATE TABLE backup_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    relative_path VARCHAR(500),
    file_size BIGINT,
    sha256 VARCHAR(64),
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE site_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value CLOB,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
